apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dejj3b7ua-nodejs 
  janus-idp.io/tekton: dejj3b7ua-nodejs
  backstage.io/kubernetes-id: dejj3b7ua-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dejj3b7ua-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml