apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dejj3b7ua-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dejj3b7ua-nodejs 
  name: dejj3b7ua-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dejj3b7ua-nodejs 
